<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Obrazky\Ikona_OctaBeats.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Obrazky\Ikona_App_Theme.png" />
    <None Remove="Resources\Obrazky\Ikona_Dalsi.png" />
    <None Remove="Resources\Obrazky\Ikona_Dalsi_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Error_Image.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost._Frame_1.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost._Frame_2.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost._Frame_3.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost._Frame_4.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_1.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_1_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_2.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_2_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_3.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_3_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_4.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_4_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_5.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_5_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Informace.png" />
    <None Remove="Resources\Obrazky\Ikona_Jazyk.png" />
    <None Remove="Resources\Obrazky\Ikona_Metadata_Editor.ico" />
    <None Remove="Resources\Obrazky\Ikona_OctaBeats.ico" />
    <None Remove="Resources\Obrazky\Ikona_O_Nas.png" />
    <None Remove="Resources\Obrazky\Ikona_Playlist_Editor.ico" />
    <None Remove="Resources\Obrazky\Ikona_Pozastavit.png" />
    <None Remove="Resources\Obrazky\Ikona_Pozastavit_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Prebal_Obrazek.png" />
    <None Remove="Resources\Obrazky\Ikona_Predchozi.png" />
    <None Remove="Resources\Obrazky\Ikona_Predchozi_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Prehrat.png" />
    <None Remove="Resources\Obrazky\Ikona_Prehrat_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Pridat.png" />
    <None Remove="Resources\Obrazky\Ikona_Pridat_Soubor.png" />
    <None Remove="Resources\Obrazky\Ikona_Sipka.png" />
    <None Remove="Resources\Obrazky\Ikona_Sipka_Dark.png" />
    <None Remove="Resources\Obrazky\Ikona_Stahnout.png" />
    <None Remove="Resources\Obrazky\Ikona_Svetly_Rezim.png" />
    <None Remove="Resources\Obrazky\Ikona_Sync.png" />
    <None Remove="Resources\Obrazky\Ikona_Tmavy_Rezim.png" />
    <None Remove="Resources\Obrazky\Ikona_Ukoncit_Aplikaci.png" />
    <None Remove="Resources\Obrazky\Ikona_Vymazat.png" />
    <None Remove="Resources\Obrazky\Ikona_Vymazat_Vsechno.png" />
    <None Remove="Resources\Obrazky\Ikona_Zmenit_Jazyk.ico" />
    <None Remove="Resources\Obrazky\Vlajka_CZ.png" />
    <None Remove="Resources\Obrazky\Vlajka_US.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Obrazky\Ikona_Dalsi_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_1_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_2_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_3_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_4_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_5_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Metadata_Editor.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_OctaBeats.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Playlist_Editor.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Pozastavit_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Prebal_Obrazek.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Predchozi_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Prehrat_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Sipka.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Sipka_Dark.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Stahnout.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Svetly_Rezim.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Tmavy_Rezim.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Obrazky\Ikona_App_Theme.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Jazyk.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Obrazky\Ikona_Dalsi.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_5.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Informace.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_O_Nas.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Pozastavit.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Predchozi.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Prehrat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Resources\JazykoveVerze\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\JazykoveVerze\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Obrazky\Ikona_Error_Image.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Pridat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Pridat_Soubor.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Sync.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Ukoncit_Aplikaci.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Vymazat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Vymazat_Vsechno.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Zmenit_Jazyk.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Vlajka_CZ.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Vlajka_US.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
