<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Obrazky\Ikona_Dalsi.png" />
    <None Remove="Resources\Obrazky\Ikona_Error_Image.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost._Frame_1.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost._Frame_2.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost._Frame_3.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost._Frame_4.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_1.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_2.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_3.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_4.png" />
    <None Remove="Resources\Obrazky\Ikona_Hlasitost_Frame_5.png" />
    <None Remove="Resources\Obrazky\Ikona_Pozastavit.png" />
    <None Remove="Resources\Obrazky\Ikona_Predchozi.png" />
    <None Remove="Resources\Obrazky\Ikona_Prehrat.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Obrazky\Ikona_Dalsi.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_5.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Pozastavit.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Predchozi.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Prehrat.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\JazykoveVerze\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\JazykoveVerze\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Obrazky\Ikona_Error_Image.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Obrazky\Ikona_Hlasitost_Frame_4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
